### ISSUE TITLE
Add snapping as a float variable

### ISSUE THREAD

**Issue by dnomadb** [mapbox/colonel-mercator#5]
To enable flexible snapping, make the snapping option a float from 0 to 1, where 0 == snap down, 0.5 == snap to closest, and 1 == snap up.

cc @perrygeo

**Comment by perrygeo** [comment]
Just curious: Why floats instead of `--snap=closest|up|down`?

**Comment by dnomadb** [comment]
@perrygeo to enable weighted snapping as outlined here: https://github.com/mapbox/pxm/issues/454 - the number could be anywhere in between.

**Comment by dnomadb** [comment]
Integrated with #6
